pyproject.toml, src/arviz_stats/accessors.py, tests/base/test_stats.py
This is related to arviz-devs/arviz-plots#23
----
📚 Documentation preview 📚: https://arviz-stats--1.org.readthedocs.build/en/1/
=> add ecdf accessor

.github/workflows/test.yml, pyproject.toml, src/arviz_stats/accessors.py, src/arviz_stats/base/density.py, tox.ini
- always return arrays of grid_len
- import gaussian from scipy.signal.windows
- apply reducing functions in dataset accessor only to dims that are present in each variable
----
📚 Documentation preview 📚: https://arviz-stats--2.org.readthedocs.build/en/2/
=> Some maintenance and fixes

.github/workflows/publish.yml
----
📚 Documentation preview 📚: https://arviz-stats--5.org.readthedocs.build/en/5/
=> use environment for publish action

.github/workflows/publish.yml
----
📚 Documentation preview 📚: https://arviz-stats--6.org.readthedocs.build/en/6/
=> try fixing workflow

.github/workflows/publish.yml
----
📚 Documentation preview 📚: https://arviz-stats--7.org.readthedocs.build/en/7/
=> Fix pypi publishing

.github/dependabot.yml, .github/workflows/test.yml, .pre-commit-config.yaml, .pylintrc, CODE_OF_CONDUCT.md, LICENSE, docs/source/background.md, docs/source/conf.py, pyproject.toml, src/arviz_stats/_version.py, src/arviz_stats/accessors.py, src/arviz_stats/base/__init__.py, src/arviz_stats/base/array.py, src/arviz_stats/base/core.py, src/arviz_stats/base/density.py, src/arviz_stats/base/diagnostics.py, src/arviz_stats/base/stats_utils.py, src/arviz_stats/numba/array.py, src/arviz_stats/numba/diagnostics.py, src/arviz_stats/numba/intervals.py, src/arviz_stats/utils.py, tests/base/test_diagnostics.py, tests/base/test_stats.py, tests/base/test_stats_utils.py, tests/test_utils.py
----
📚 Documentation preview 📚: https://arviz-stats--12.org.readthedocs.build/en/12/
=> workflow updates and run pre-commit

src/arviz_stats/accessors.py
----
📚 Documentation preview 📚: https://arviz-stats--19.org.readthedocs.build/en/19/
=> work on accessor return types

docs/source/api/index.md, src/arviz_stats/accessors.py, src/arviz_stats/base/array.py, src/arviz_stats/base/core.py, src/arviz_stats/base/dataarray.py, src/arviz_stats/base/stats_utils.py, tests/base/test_stats_utils.py
Working first draft for compute_ranks function.
----
📚 Documentation preview 📚: https://arviz-stats--17.org.readthedocs.build/en/17/
=> add compute_ranks function

src/arviz_stats/base/dataarray.py, src/arviz_stats/validate.py
Not to be merged yet, still have to figure out splitting of functionality
between einstats and here.
----
📚 Documentation preview 📚: https://arviz-stats--22.org.readthedocs.build/en/22/
=> Support for ess/mcse/ps_min_ss along single dimension

src/arviz_stats/accessors.py, src/arviz_stats/base/array.py, src/arviz_stats/base/core.py, src/arviz_stats/base/dataarray.py
----
📚 Documentation preview 📚: https://arviz-stats--21.org.readthedocs.build/en/21/
=> get_bins dataarray version

pyproject.toml, src/arviz_stats/_version.py
----
📚 Documentation preview 📚: https://arviz-stats--37.org.readthedocs.build/en/37/
=> pin xarray-datatree and prepare 0.3 release

docs/source/conf.py, pyproject.toml, src/arviz_stats/accessors.py, src/arviz_stats/numba/diagnostics.py, tests/test_accessors.py
Next domino to fall. So far seems like no issues.
Related to https://github.com/arviz-devs/arviz-base/issues/14
----
📚 Documentation preview 📚: https://arviz-stats--35.org.readthedocs.build/en/35/
=> Use datatree from xarray

docs/source/api/index.md, src/arviz_stats/__init__.py, src/arviz_stats/sampling_diagnostics.py
----
📚 Documentation preview 📚: https://arviz-stats--47.org.readthedocs.build/en/47/
=> Add Rhat and MCSE functions

src/arviz_stats/sampling_diagnostics.py
----
📚 Documentation preview 📚: https://arviz-stats--49.org.readthedocs.build/en/49/
=> fix docstring mcse

docs/source/api/index.md, src/arviz_stats/__init__.py, src/arviz_stats/accessors.py, src/arviz_stats/base/dataarray.py, src/arviz_stats/manipulation.py
Not very happy with the name "manipulation". We can change it later
----
📚 Documentation preview 📚: https://arviz-stats--48.org.readthedocs.build/en/48/
=> Add thin function

docs/source/api/index.md, src/arviz_stats/bayes_factor.py, tests/test_bayes_factor.py
This PR address this issue #45 
----
📚 Documentation preview 📚: https://arviz-stats--52.org.readthedocs.build/en/52/
=> Add bayes_factor function

src/arviz_stats/helper_stats.py
fix #59
----
📚 Documentation preview 📚: https://arviz-stats--60.org.readthedocs.build/en/60/
=> isotonic_ fit, work on datatrees

src/arviz_stats/psense.py, tests/test_psense.py
pinging @n-kall, to be in sync with priorsense.
----
📚 Documentation preview 📚: https://arviz-stats--57.org.readthedocs.build/en/57/
=> psense: Enhance citations and references to external information sources.

src/arviz_stats/helper_stats.py
----
📚 Documentation preview 📚: https://arviz-stats--61.org.readthedocs.build/en/61/
=> utils functions for rootogram

src/arviz_stats/helper_stats.py
----
📚 Documentation preview 📚: https://arviz-stats--64.org.readthedocs.build/en/64/
=> change var_names argument to data_pairs for isotonic fit

src/arviz_stats/helper_stats.py
----
📚 Documentation preview 📚: https://arviz-stats--66.org.readthedocs.build/en/66/
=> Ensure we preserve number of observations

src/arviz_stats/ecdf_utils.py
----
📚 Documentation preview 📚: https://arviz-stats--69.org.readthedocs.build/en/69/
=> Add functions for ecdf_pit and simultaneuous confidence bands computations

pyproject.toml
----
📚 Documentation preview 📚: https://arviz-stats--72.org.readthedocs.build/en/72/
=> update dependencies for release

src/arviz_stats/ecdf_utils.py
----
📚 Documentation preview 📚: https://arviz-stats--75.org.readthedocs.build/en/75/
=> Add randomized PIT

src/arviz_stats/accessors.py, src/arviz_stats/ecdf_utils.py
----
📚 Documentation preview 📚: https://arviz-stats--76.org.readthedocs.build/en/76/
=> Simplify rank_ecdf

docs/source/api/index.md, src/arviz_stats/__init__.py, src/arviz_stats/loo.py, src/arviz_stats/summary.py, tests/test_loo.py
----
📚 Documentation preview 📚: https://arviz-stats--78.org.readthedocs.build/en/78/
=> Add Compare

src/arviz_stats/ecdf_utils.py
----
📚 Documentation preview 📚: https://arviz-stats--80.org.readthedocs.build/en/80/
=> Transform PIT values into ETI coverage values

pyproject.toml, src/arviz_stats/_version.py
----
📚 Documentation preview 📚: https://arviz-stats--81.org.readthedocs.build/en/81/
=> bump release

pyproject.toml, src/arviz_stats/_version.py
----
📚 Documentation preview 📚: https://arviz-stats--83.org.readthedocs.build/en/83/
=> after release changes

docs/source/api/index.md, src/arviz_stats/__init__.py, src/arviz_stats/base/array.py, src/arviz_stats/base/dataarray.py, src/arviz_stats/base/diagnostics.py, src/arviz_stats/loo.py, tests/test_loo.py
----
📚 Documentation preview 📚: https://arviz-stats--84.org.readthedocs.build/en/84/
=> Add loo_pit function

docs/source/api/index.md, src/arviz_stats/__init__.py, src/arviz_stats/accessors.py, src/arviz_stats/base/array.py, src/arviz_stats/base/dataarray.py, src/arviz_stats/base/diagnostics.py, src/arviz_stats/sampling_diagnostics.py, tests/base/test_diagnostics.py
----
📚 Documentation preview 📚: https://arviz-stats--87.org.readthedocs.build/en/87/
=> Add Nested rhat

docs/source/api/index.md, src/arviz_stats/__init__.py, src/arviz_stats/base/diagnostics.py, src/arviz_stats/loo.py, src/arviz_stats/utils.py, tests/test_loo.py
----
📚 Documentation preview 📚: https://arviz-stats--89.org.readthedocs.build/en/89/
=> Add loo expectations and metrics

src/arviz_stats/loo.py, tests/test_loo.py
----
📚 Documentation preview 📚: https://arviz-stats--90.org.readthedocs.build/en/90/
=> Add more test and example for loo_metrics

src/arviz_stats/helper_stats.py
----
📚 Documentation preview 📚: https://arviz-stats--92.org.readthedocs.build/en/92/
=> isotonic: add group option

pyproject.toml
Fixes #68 
----
📚 Documentation preview 📚: https://arviz-stats--93.org.readthedocs.build/en/93/
=> MInor: Fix Sphinx version

src/arviz_stats/ecdf_utils.py
----
📚 Documentation preview 📚: https://arviz-stats--94.org.readthedocs.build/en/94/
=> Add group argument to difference_ecdf_pit

src/arviz_stats/base/dataarray.py
----
📚 Documentation preview 📚: https://arviz-stats--97.org.readthedocs.build/en/97/
=> autocorr, do not add coords

docs/source/index.md
----
📚 Documentation preview 📚: https://arviz-stats--105.org.readthedocs.build/en/105/
=> fix link eabm

src/arviz_stats/base/dataarray.py, src/arviz_stats/base/diagnostics.py
see https://github.com/arviz-devs/arviz-plots/pull/105, but we also have to make sure we incorporate
all the latest corrections we recently merged in current ArviZ (https://github.com/arviz-devs/arviz/pull/2167)
----
📚 Documentation preview 📚: https://arviz-stats--44.org.readthedocs.build/en/44/
=> start ess related improvements

src/arviz_stats/base/dataarray.py, tests/base/test_diagnostics.py
----
📚 Documentation preview 📚: https://arviz-stats--109.org.readthedocs.build/en/109/
=> fix ess prob validation

.gitignore, pyproject.toml
----
📚 Documentation preview 📚: https://arviz-stats--113.org.readthedocs.build/en/113/
=> Fix HDF error in doc build

src/arviz_stats/bayes_factor.py, tests/test_bayes_factor.py
* Extended the bayes_factor function to work with multiple variables.
* Used xarray's interp method to handle interpolation.
* Updated the test cases to validate multi-variable functionality.
* Closes #96 
----
📚 Documentation preview 📚: https://arviz-stats--104.org.readthedocs.build/en/104/
=> Improved bayes_factor for multi-variable support

docs/source/api/index.md, metrics.py, src/arviz_stats/__init__.py, src/arviz_stats/loo.py, src/arviz_stats/metrics.py, tests/test_metrics.py
Closes #118 
----
📚 Documentation preview 📚: https://arviz-stats--119.org.readthedocs.build/en/119/
=> Add wasserstein distance and KL-divergence

src/arviz_stats/base/array.py, src/arviz_stats/base/density.py, tests/base/test_stats.py
----
📚 Documentation preview 📚: https://arviz-stats--143.org.readthedocs.build/en/143/
=> raise when extra kwargs present in hdi&kde, add test for eti,hdi,kde&histogram

src/arviz_stats/base/diagnostics.py
Closes #130 
----
📚 Documentation preview 📚: https://arviz-stats--159.org.readthedocs.build/en/159/
=> add warnings for finite data and fix computation for discrete data

src/arviz_stats/helper_stats.py
----
📚 Documentation preview 📚: https://arviz-stats--167.org.readthedocs.build/en/167/
=> Compute isotonic regression for categorical and ordinal data

docs/source/api/index.md, src/arviz_stats/__init__.py, src/arviz_stats/accessors.py, src/arviz_stats/base/array.py, src/arviz_stats/base/dataarray.py, src/arviz_stats/base/density.py, src/arviz_stats/visualization.py, tests/test_summary.py
Closes #170 
----
📚 Documentation preview 📚: https://arviz-stats--171.org.readthedocs.build/en/171/
=> Add functionality to compute quantile dots

src/arviz_stats/loo/compare.py
See https://github.com/arviz-devs/arviz/pull/2477
----
📚 Documentation preview 📚: https://arviz-stats--198.org.readthedocs.build/en/198/
=> Fix typing issue in `compare()`

docs/source/array_stats_only.ipynb, docs/source/index.md, docs/source/overview.ipynb
Fixes some typos and grammatical stuff in the docs
----
📚 Documentation preview 📚: https://arviz-stats--197.org.readthedocs.build/en/197/
=> Improve documentation 

src/arviz_stats/ecdf_utils.py
This makes computations more reliable for values of `ci_prob` closer  to 1
----
📚 Documentation preview 📚: https://arviz-stats--199.org.readthedocs.build/en/199/
=> make hypergeom computation more robust

pyproject.toml, src/arviz_stats/ecdf_utils.py, tests/test_ecdf_utils.py
----
📚 Documentation preview 📚: https://arviz-stats--211.org.readthedocs.build/en/211/
=> Use lookup table for hypergeometric computation instead of numba

src/arviz_stats/base/array.py, src/arviz_stats/base/dataarray.py, src/arviz_stats/base/diagnostics.py, tests/test_minimal.py
----
📚 Documentation preview 📚: https://arviz-stats--215.org.readthedocs.build/en/215/
=> automatically compute reff for pareto_khat
