- src/arviz_stats/accessors.py
- src/arviz_stats/base/array.py
- src/arviz_stats/base/dataarray.py
Adds thinning based on ESS as discussed [Säilynoja 2022](https://arxiv.org/abs/2103.10522) and this vignette https://mc-stan.org/posterior/reference/thin_draws.html
I tried with a couple of examples and it works, but not sure I am adding all that is needed. Or if everything is in the right place
----
📚 Documentation preview 📚: https://arviz-stats--18.org.readthedocs.build/en/18/
> Add thinning

- src/arviz_stats/base/array.py
- src/arviz_stats/base/density.py
As discussed in https://github.com/arviz-devs/arviz-stats/pull/28#issuecomment-2414524683, HDI method `agg_nearest` is not very useful as an HDI estimator compared to our other options. From that comment:
> `agg_nearest` seems to be not so similar to `nearest` at all. It will only be similar when `multimodal` would return a single interval. Otherwise, it also includes all the intervals between the HDI intervals and can contain much more probability than the requested "hdi_prob". Personally, I don't see a use for `agg_nearest`; I see it as being similar to reaching for a CDF estimated from a KDE instead of an ECDF. I think the smoothing would in general only make the estimate worse. If something similar to `nearest` that forces contiguity but uses "bin centers" is really what's desired, a …
> Remove HDI method agg_nearest

- src/arviz_stats/base/density.py
- tests/base/test_stats.py
As discussed in https://github.com/arviz-devs/arviz-stats/pull/28#discussion_r1797785930, the KDE is not always normalized to exactly 1. This PR ensures that it is and adds a corresponding test.
----
📚 Documentation preview 📚: https://arviz-stats--30.org.readthedocs.build/en/30/
> Ensure KDE is normalized

- .pre-commit-config.yaml
- src/arviz_stats/accessors.py
- tests/base/test_diagnostics.py
- tests/base/test_stats_utils.py
- tests/test_accessors.py
- tests/test_psense.py
- tests/test_utils.py
- tox.ini
Some improvements to behaviour of DataTree accessor, plus adding some tests for accessors.
----
📚 Documentation preview 📚: https://arviz-stats--32.org.readthedocs.build/en/32/
> Improve behaviour of DataTree accessor

- src/arviz_stats/base/array.py
- src/arviz_stats/base/core.py
- src/arviz_stats/base/dataarray.py
- src/arviz_stats/base/density.py
- tests/base/test_stats.py
This PR implements the improvements to HDI suggested in https://github.com/arviz-devs/arviz/issues/2394, with a few differences:
- Supporting passing an array of HDI probabilities is left for a future PR.
- Circular support for continuous multimodal HDI is included.
- When more intervals than `max_modes` are computed, now the `max_modes` highest probability intervals are returned instead of just the ones that are lowest on the real line.
----
📚 Documentation preview 📚: https://arviz-stats--28.org.readthedocs.build/en/28/
> Improvements to multimodal HDI

- docs/source/api/index.md
- docs/source/conf.py
- src/arviz_stats/accessors.py
- src/arviz_stats/base/array.py
- src/arviz_stats/base/dataarray.py
- src/arviz_stats/base/diagnostics.py
- src/arviz_stats/psense.py
- tests/test_psense.py
This also:
* Reorder arguments, matching the order in arviz-plots. i.e. first general arguments like var_names and coords and then specific ones. Is this what we want? Or we want first the specific ones? 
* Add `psense` and `psense_summary` to the API documentation
----
📚 Documentation preview 📚: https://arviz-stats--34.org.readthedocs.build/en/34/
> Add more arguments to psense_summary

- src/arviz_stats/psense.py
We used to call this function "new_ds" which was okayish for an internal function, but not a very informative name for a user-exposed function.
----
📚 Documentation preview 📚: https://arviz-stats--38.org.readthedocs.build/en/38/
> move in power_scale_dataset from arviz-plots

- src/arviz_stats/psense.py
----
📚 Documentation preview 📚: https://arviz-stats--53.org.readthedocs.build/en/53/
> Add separated prior and likelihood groups

- src/arviz_stats/psense.py
----
📚 Documentation preview 📚: https://arviz-stats--54.org.readthedocs.build/en/54/
> Priorsense function allow inferencedata as input

- docs/source/api/index.md
- src/arviz_stats/__init__.py
- src/arviz_stats/base/core.py
- src/arviz_stats/base/dataarray.py
- src/arviz_stats/summary.py
Closes #11 
This adds the basic functionality for the `summary` function. It is still not on par with the `summary` function from old ArviZ, but it is better than nothing. ~Currently, the output is a dataset. To get a Pandas' DataFrame we need arviz-devs/arviz-base#25~
In the old arviz we had a `kind` argument and a `stat_focus` argument. The combination of both specifies which stats/diagnostics were computed. Now we achieve the same with just the `kind` argument. For instance `kind="all"` is the equivalent of the old `kind=all` and `stats_focus="mean"` and kind  `kind="all_median"` is the equivalent of the old `kind=all` and `stats_focus="median"`. Having a single argument seems clear to me.
One source of inconsistency is that previously we returned the `hdi` if `stat_focus="mean"` and …
> Add summary function

- docs/source/api/index.md
- src/arviz_stats/accessors.py
- src/arviz_stats/base/dataarray.py
This is related to https://github.com/arviz-devs/arviz-plots/pull/153. 
Added an `autocorr` accessor to the `_BaseAccessor` class, similar to the existing `hdi` and `ess` accessors. 
----
📚 Documentation preview 📚: https://arviz-stats--65.org.readthedocs.build/en/65/
> Add autocorr accessor to _BaseAccessor class

- pyproject.toml
Documentation building is failing, not sure why at the moment so adding upper bound for sphinx version
----
📚 Documentation preview 📚: https://arviz-stats--67.org.readthedocs.build/en/67/
> Add upper bound sphinx

- src/arviz_stats/base/diagnostics.py
ps_tail_length can result in a tail length longer than the number of draws if the r_eff is very small. This cap the tail at 20% of the total number of draws.
----
📚 Documentation preview 📚: https://arviz-stats--79.org.readthedocs.build/en/79/
> Cap tail at 20%

- src/arviz_stats/loo.py
- tests/test_loo.py
This also adds a single `var_names` argument instead of `y_obs` and `y_pred`. It will work fine when the observed and predicted variables share the same name.
----
📚 Documentation preview 📚: https://arviz-stats--85.org.readthedocs.build/en/85/
> Add randomized loo_pit

- src/arviz_stats/__init__.py
- src/arviz_stats/bayes_factor.py
* As you suggested [Link](https://github.com/arviz-devs/arviz-stats/pull/46#issuecomment-2601783660) on Jan 20, this PR replaces the `_DensityBase` instantiation logic with the KDE accessor for density computation.
* Avoided the use of `_DensityBase` for KDE computation.
* Added `.azstats.kde()` accessor to compute densities and grids directly.
* Updated Bayes factor calculation to use the new KDE accessor.
* Simplified posterior/prior extraction using idata.posterior[var_name].
* Closes #55 
----
📚 Documentation preview 📚: https://arviz-stats--95.org.readthedocs.build/en/95/
> Update KDE computation & Bayes factor implementation (#55)

- src/arviz_stats/accessors.py
- src/arviz_stats/base/array.py
- src/arviz_stats/base/diagnostics.py
- src/arviz_stats/sampling_diagnostics.py
- tests/base/test_diagnostics.py
This extends `rhat_nested` to support all the rank normalisation methods on `rhat`
----
📚 Documentation preview 📚: https://arviz-stats--102.org.readthedocs.build/en/102/
> Adding rank normalisation methods to rhat_nested

- docs/source/api/index.md
- src/arviz_stats/__init__.py
- src/arviz_stats/loo.py
- src/arviz_stats/utils.py
- tests/test_loo.py
This PR adds a new function, `loo_approximate_posterior`, that extends PSIS-LOO-CV to approximate posteriors from variational inference and other methods.
----
📚 Documentation preview 📚: https://arviz-stats--101.org.readthedocs.build/en/101/
> Add loo_approximate_posterior function

- src/arviz_stats/helper_loo.py
- src/arviz_stats/loo.py
- tests/test_loo.py
Support for mis-matched variable names in `loo_pit` and corresponding test in `test_loo.py`.
resolves: [86](https://github.com/arviz-devs/arviz-stats/issues/86)
----
📚 Documentation preview 📚: https://arviz-stats--115.org.readthedocs.build/en/115/
> Add support for different variable names in loo_pit

- docs/source/api/index.md
- src/arviz_stats/__init__.py
- src/arviz_stats/base/array.py
- src/arviz_stats/base/diagnostics.py
- src/arviz_stats/loo.py
- src/arviz_stats/metrics.py
- src/arviz_stats/utils.py
- tests/test_metrics.py
This adds a series of metrics mirroring those already available in `loo_metrics`. To ease comparison between predictive metrics and this one, they are defined in the same way. 
~I guess for a future PR we may want to move the computation to the array interface, similar to what we already have for r2_score~.
----
📚 Documentation preview 📚: https://arviz-stats--121.org.readthedocs.build/en/121/
> Add "regular" metrics

- src/arviz_stats/loo.py
- tests/test_loo.py
The randomisation routine was cumbersome and contained errors. This is a more straightforward implementation and closer to what is done in posterior package. Not sure this is the best one from an xarray perspective. The test `test_loo_pit_different_names` is failing I think the problem is that the dimensions are not aligned when doing 
sel_min[var] = posterior_predictive[pp_var_names[i]] < observed_data[var]
sel_sup[var] = posterior_predictive[pp_var_names[i]] == observed_data[var]
I will not have the time to look at this during the weekend, so if someone wants to clean this, go ahead. Otherwise, I can continue with this next week.
----
📚 Documentation preview 📚: https://arviz-stats--120.org.readthedocs.build/en/120/
> Fix loo pit randomization

- src/arviz_stats/ecdf_utils.py
- tests/test_ecdf_utils.py
I am adding the method for the envelope that takes into account multiple chains. I am implementing the cdf of the hypergeometric using numba, as the one in scipy is too slow for this. I visually compared the results with the example in bayesplot, and there is no clear difference. Results are also visually equivalent when using the custom function or the one from scipy. I added a small test comparing the computation in scipy and the custom cdf. 
I am removing the optimization method as it is currently slower than the simulation method, and the simulation method seems to be fast enough so far. We can later revisit this.
One more thing, I need to check in detail, but I think the default in bayesplot for the ci_prob when computing the envelope is 0.99, maybe the 0.94  will lead to too many …
> Add method for multiple chains, remove optimization method

- src/arviz_stats/loo/helper_loo.py
- src/arviz_stats/loo/loo.py
- src/arviz_stats/loo/loo_expectations.py
- src/arviz_stats/loo/loo_pit.py
- src/arviz_stats/loo/loo_subsample.py
- src/arviz_stats/loo/reloo.py
- src/arviz_stats/utils.py
- tests/test_helper_loo.py
- tests/test_loo.py
- tests/test_reloo.py
This PR adds support for log weights throughout the `loo` module, allowing users to provide pre-computed smoothed log weights or pass an existing `ELPDData` object into the function enabling the storage and reuse of log weights across function calls.
Added `log_weights` parameter to:
- `loo()` (just accepts pre-computed log weights, not ELPDData object)
- `loo_subsample()`
- `update_subsample()`
- `loo_expectations()` 
- `loo_pit()` 
- `reloo()` 
- `loo_metrics()` 
Note that `loo_moment_match` is not included here yet. Waiting to re-organize the function and then introduce a new argument for log weights.
Log weights can be provided in two formats:
- As a `DataArray` with the same shape as the log likelihood data
- As an `ELPDData` object from a previous LOO-based computation
The LOO …
> Log Weights API change for LOO functions

- src/arviz_stats/loo/loo_expectations.py
- tests/test_loo.py
This PR fixes a bug where `loo_metrics` would fail with `ValueError: All tail values are the same` when computing function-specific k-hat values via `_get_function_khat`.
Changes:
- Added try-except handling in `_get_function_khat` to catch the error from `pareto_khat` when tail values are identical
- Fall back to importance ratio's k-hat (`khat_r`) when function-specific k-hat (`khat_hr`) computation fails
- Added validation for edge cases: constant, binary, or non-finite function values
I wanted to note that we also have a `try...except` block around `khat_r` because in `diagnostics.py` for `_pareto_khat`, when we catch the error that all tail values are the same, we do not assign `np.nan` to it. So, `_get_function_khat` could potentially fail here as well. It's worth noting that in the …
> Fix function specific k-hat computation 

- docs/source/api/index.md
- src/arviz_stats/__init__.py
- src/arviz_stats/loo/__init__.py
- src/arviz_stats/loo/helper_loo_kfold.py
- src/arviz_stats/loo/loo_kfold.py
- src/arviz_stats/loo/wrapper.py
- tests/test_helper_loo_kfold.py
- tests/test_loo_kfold.py
This PR adds `loo_kfold` functionality for k-fold cross validation with helpers in `helper_loo_kfold.py` and a test suite for the main function and helpers. Made some slight changes to the `SamplingWrapper` to better accomodate k-fold CV and tracking refits.
We follow the R module [loo-kfold](https://github.com/stan-dev/rstanarm/blob/2ec70ba7d2280749bef4fba2b7c5a7334dd9bba7/R/loo-kfold.R) closely and use [kfold-helpers](https://github.com/stan-dev/loo/blob/master/R/kfold-helpers.R) as inspiration for helper functions.
---
Resolves [#150](https://github.com/arviz-devs/arviz-stats/issues/150)
----
📚 Documentation preview 📚: https://arviz-stats--158.org.readthedocs.build/en/158/
> Add loo_kfold for exact K-fold cross validation 

- .pylintrc
- src/arviz_stats/loo/helper_loo.py
- src/arviz_stats/loo/loo_moment_match.py
- tests/test_helper_loo.py
- tests/test_loo.py
This PR refactors the `loo_moment_match` function to improve modularity, maintainability, and usability.
Changes
- The `upars` parameter is now optional and will attempt to use the `unconstrained_posterior` group from the input data if not provided
- Extracted the core moment matching logic into separate helper functions:
- `_loo_moment_match_i`: Handles moment matching for a single observation now
- `_update_quantities_i`: Recalculates importance weights and Pareto k after transformations
- `_update_loo_data_i`: Moved this from `helper_loo.py` into the main `loo_moment_match.py` file. I think it makes sense to have all of the update data functions here for clarity. 
Had to increase the max line length for a module from 1000 to 1500 with the addition of `_update_loo_data_i` to the main …
> Fix loo_moment_match to be more modular

- docs/source/api/index.md
- src/arviz_stats/__init__.py
- src/arviz_stats/accessors.py
- src/arviz_stats/base/array.py
- src/arviz_stats/base/core.py
- src/arviz_stats/base/dataarray.py
- src/arviz_stats/summary.py
- tests/test_summary.py
closes #9 
For the mode computation I use the half-sample method, instead of the max density from a kde. According to what I read and a few tests it seems to provide reasonable results (even for circular variable without doing any change). It only returns a single mode.
This PR assumes we want the mode computation to behave like xarray's mean (or similar functions). So
```python
dt = azb.load_arviz_data("centered_eight").posterior
dt.azstats.mode()
``` 
returns 3 values, one for mu, theta, and tau. 
And 
```python
dt.azstats.mode(dim=["chain", "draw"])
``` 
returns 10 values, one for mu and tau, and eight for theta
This currently fails 
```python
dt.azstats.mode(dim=["school"])
``` 
If we were computing the mean, the result would be 3 arrays of shape (4, 500), one per variable.
----
📚 …
> add mode computation

- src/arviz_stats/loo/helper_loo.py
- src/arviz_stats/loo/loo.py
- src/arviz_stats/loo/loo_approximate_posterior.py
- tests/test_loo.py
This adds support for log-Jacobian adjustments when computing PSIS-LOO-CV, enabling correct ELPD calculation for models fitted on transformed response variables.
Changes
- Adds optional `log_jacobian` parameter to `loo` and `loo_approximate_posterior`
- Validation and dimension checking for Jacobian input via `_check_log_jacobian` helper
- Adjusts both pointwise ELPD values and aggregate metrics when Jacobian is provided
- Added some validation for pre-computed `log_weights` and `pareto_k` since we're allowing those now
Since this is backward compatible, we can keep working on improvements for this. It might make sense to allow `np.array` log Jacobian inputs as well. Figured we could start with the standard `DataArray` input first. 
Adding the Jacobian adjustment to `loo_subsample` needs …
> Add support for Jacobian adjustment to elpd_loo values

- src/arviz_stats/loo/compare.py
- tests/test_loo.py
This adds more informative errors for `compare()`. See the discussion in https://github.com/stan-dev/loo/issues/296 for aligning certain error messages.
---
Resolves [#179](https://github.com/arviz-devs/arviz-stats/issues/179)
----
📚 Documentation preview 📚: https://arviz-stats--184.org.readthedocs.build/en/184/
> Add more informative errors for model comparison in `compare()`

- src/arviz_stats/loo/compare.py
Improve the API formatting for `arviz_stats.compare`:
https://arviz-stats.readthedocs.io/en/latest/api/generated/arviz_stats.compare.html
For the **Returns** section, I followed the format in `arviz_stats.loo`:
https://arviz-stats.readthedocs.io/en/latest/api/generated/arviz_stats.loo.html
----
📚 Documentation preview 📚: https://arviz-stats--202.org.readthedocs.build/en/202/
> DOC: Improve the API formatting for `arviz_stats.compare`

- pyproject.toml
I noticed slowdowns with the recently released version of numba, 0.62.0 
----
📚 Documentation preview 📚: https://arviz-stats--210.org.readthedocs.build/en/210/
> pin numba version

- src/arviz_stats/loo/loo_approximate_posterior.py
Fixes a bug in the sign for the PSIS inputs for `loo_approximate_posterior()`. Now we get the correct `p_loo` values. Improves the example in the docstring as well. 
Found this issue out when I was creating the tutorial for EABM for `loo_subsample()` and `loo_approximate_posterior()`. I couldn't match the same results from the R example using the Laplace approximation for the approximate posterior case. 
----
📚 Documentation preview 📚: https://arviz-stats--213.org.readthedocs.build/en/213/
> Fix the sign of PSIS inputs in `loo_approximate_posterior()`

- src/arviz_stats/loo/compare.py
- src/arviz_stats/loo/loo_subsample.py
- src/arviz_stats/utils.py
- tests/test_loo.py
This adds model comparison support for subsampled LOO results, matching the behavior of the `loo` package.
When using `loo_subsample()`, the previous `compare()` returned NaN values for the difference standard error (`dse`) and didn't report a `subsample_dse` when using subsampled models. Subsampled results store NaN for non-sampled observations, and the pointwise variance calculation `np.var(diff)` propagated these NaNs which caused issues with `dse`. The `loo` package handles this by storing subsample metadata, which we track in functions for subsampling in `helper_loo.py`, and using a difference-of-estimators approach for variance calculation.
Also adds the same warnings from the `loo` package when comparing full LOO to subsampled LOO, and when comparing subsampled LOO models with …
> Add subsampling support in `compare()`
